// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuAhT_hy-mw8-TS5FzMf15LwKSEuWCjYg',
    appId: '1:476402096447:web:880ead6ce2ce9da23f1b8a',
    messagingSenderId: '476402096447',
    projectId: 'shosestore-60804',
    authDomain: 'shosestore-60804.firebaseapp.com',
    storageBucket: 'shosestore-60804.appspot.com',
    measurementId: 'G-EM02EL80QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrtuJlSkqPLaQtJQQGY1VztDvA1c7q7cQ',
    appId: '1:476402096447:android:aeb941c0587288c93f1b8a',
    messagingSenderId: '476402096447',
    projectId: 'shosestore-60804',
    storageBucket: 'shosestore-60804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHH3qAhYf5NkcYhJxejD5_NEAGODKaiHQ',
    appId: '1:476402096447:ios:841d78bc61b698593f1b8a',
    messagingSenderId: '476402096447',
    projectId: 'shosestore-60804',
    storageBucket: 'shosestore-60804.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHH3qAhYf5NkcYhJxejD5_NEAGODKaiHQ',
    appId: '1:476402096447:ios:841d78bc61b698593f1b8a',
    messagingSenderId: '476402096447',
    projectId: 'shosestore-60804',
    storageBucket: 'shosestore-60804.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuAhT_hy-mw8-TS5FzMf15LwKSEuWCjYg',
    appId: '1:476402096447:web:0d0256cfea579fea3f1b8a',
    messagingSenderId: '476402096447',
    projectId: 'shosestore-60804',
    authDomain: 'shosestore-60804.firebaseapp.com',
    storageBucket: 'shosestore-60804.appspot.com',
    measurementId: 'G-RBM005CZCR',
  );
}
